### ISSUE TITLE
 AlarmScheduler.cancelAllAlarmTasks() does not delete alarms

### ISSUE THREAD

**Issue by mkhakpaki** [CarterChen247/AlarmScheduler#19]
Hi 
Thank you for this great library, 
currently upon calling  AlarmScheduler.cancelAllAlarmTasks() all alarms that are stored in  AlarmScheduler are calling adding a log row like this 
Function cancelAlarmTask() invoked
wouldn't it be better to delete alarms from the db after canceling it?

**Comment by CarterChen247** [comment]
Hi @mkhakpaki

Thank you for reaching out! 😊

Actually, when canceling an alarm, it is indeed removed from the database. You can refer to the following code:
https://github.com/CarterChen247/AlarmScheduler/blob/86e378fe2cd899fe64d142612bef1f740fb2afd3/alarmscheduler/src/main/java/com/carterchen247/alarmscheduler/AlarmSchedulerImpl.kt#L61



If adding more logs would be helpful for you, I'm more than happy to do so. Additionally, if you have any specific logs you'd like to see added or any other suggestions, please feel free to share them with me. Your feedback is greatly appreciated! 🚀

Thank you!
