### ISSUE TITLE
No context in alarm receiver

### ISSUE THREAD

**Issue by shahzeb-whizpool** [CarterChen247/AlarmScheduler#21]
alarm task should receive the context

**Comment by CarterChen247** [comment]
@shahzeb-whizpool do you mean the interface AlarmTask?
https://github.com/CarterChen247/AlarmScheduler/blob/86e378fe2cd899fe64d142612bef1f740fb2afd3/alarmscheduler/src/main/java/com/carterchen247/alarmscheduler/task/AlarmTask.kt#L4-L7
